### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by eifinger** [custom-components/breaking_changes#15]
## Version of the custom_component

0.3.3
## Describe the bug
Logs show the stacktrace below.

## `custom_updater` configuration

```yaml

breaking_changes:

```

## Debug log

```text

Traceback (most recent call last):
  File "/usr/src/app/homeassistant/helpers/entity.py", line 221, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/app/homeassistant/helpers/entity.py", line 378, in async_device_update
    await self.async_update()
  File "/config/custom_components/breaking_changes/sensor.py", line 29, in async_update
    await update_data(self.hass, self.hass.data[DOMAIN_DATA]["throttle"])
  File "/config/custom_components/breaking_changes/__init__.py", line 110, in update_data
    remoteversion = pypiversion.version.split(".")[1]
AttributeError: 'NoneType' object has no attribute 'split'

```

**Comment by eifinger** [comment]
bad stale bot!
