### ISSUE TITLE
ModuleNotFoundError: No module named 'integrationhelper'

### ISSUE THREAD

**Issue by yjajkiew** [custom-components/breaking_changes#18]
Hi,

I have installed hassio on my Rpi3 last week end and I'm starting to get used to it.
I discovered your plugin and thought it would be a nice tool to integrate into the update process of my home assistant. 

Unfortunately I can't seem to get it installed because of a dependancy error.

## Version of the custom_component
Breaking_changes v0.3.6

## My Hassio system informations
Hassio 0.99.3
Frontend version: 20190919.1 - latest
python_version v3.7.4
arch : armv7
dev : false
docker : true
hassio : true
os_name : Linux
virtualenv : false

## Describe the bug
After following the install instructions (create folder custom_components, create folder breaking_changes, adding the 4 python files) and restarting hassio I get the error "ModuleNotFoundError: No module named 'integrationhelper'". You can find more informations in the debug log below.

## Configuration
As instructed I have just added the line "breaking_changes:" in my /config/configuration.yaml

## Debug log

```
Error loading custom_components.breaking_changes. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 346, in _load_file
    module = importlib.import_module(path)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/breaking_changes/__init__.py", line 15, in <module>
    from integrationhelper import Throttle, WebClient
ModuleNotFoundError: No module named 'integrationhelper'
```

**Comment by ludeeus** [comment]
HA should install that on startup, restart a few times and it should start working

**Comment by yjajkiew** [comment]
You're totally right ! I didn't know HA could do that and now it works, thanks for your help :-)
