### ISSUE TITLE
AttributeError: 'Version' object has no attribute 'get_local_version' error in Home Assistant 0.96

### ISSUE THREAD

**Issue by gadgetchnnel** [custom-components/breaking_changes#9]
## Version of the custom_component

0.2.0

## Describe the bug
When using this component in Home Assistant 0.96 there is an "AttributeError: 'Version' object has no attribute 'get_local_version'" error in the log (full log below). The sensor still shows in Home Assistant, but I don't know if it is actually working.

## `custom_updater` configuration

```yaml

# Add configuration here
breaking_changes:
```

## Debug log

```text
2019-07-18 18:46:00 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/home/homeassistant/.homeassistant/custom_components/breaking_changes/__init__.py", line 77, in loaded_platforms
    hass, no_throttle=True
  File "/home/homeassistant/.homeassistant/custom_components/breaking_changes/__init__.py", line 95, in update_data
    await haversion.get_local_version()
AttributeError: 'Version' object has no attribute 'get_local_version'
```

**Comment by ludeeus** [comment]
It's not working.

**Comment by jokerigno** [comment]
Same issue, but different message:

> 2019-07-18 23:45:37 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.potential_breaking_changes fails
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 221, in async_update_ha_state
>     await self.async_device_update()
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 378, in async_device_update
>     await self.async_update()
>   File "/config/custom_components/breaking_changes/sensor.py", line 29, in async_update
>     await update_data(self.hass)
>   File "/config/custom_components/breaking_changes/__init__.py", line 95, in update_data
>     await haversion.get_local_version()
> AttributeError: 'Version' object has no attribute 'get_local_version'

**Comment by ludeeus** [comment]
<https://github.com/custom-components/breaking_changes/releases/tag/0.3.0> Fixes this issue.
The reason for this is that `pyhaversion` was updated in Home Assistant.

**Comment by etricky** [comment]
@ludeeus I'm still getting the same error on version 0.3.0

```
2019-07-21 22:46:40 DEBUG (MainThread) [custom_components.hacs.api] Endpoint (repository_install) called
2019-07-21 22:46:40 INFO (MainThread) [custom_components.hacs.repository] (custom-components/breaking_changes) - Starting installation
2019-07-21 22:46:42 DEBUG (MainThread) [custom_components.hacs.repository] (custom-components/breaking_changes) - Removing /config/custom_components/breaking_changes
2019-07-21 22:46:42 DEBUG (MainThread) [custom_components.hacs.repository] (custom-components/breaking_changes) - Creating /config/custom_components/breaking_changes
2019-07-21 22:46:42 DEBUG (MainThread) [custom_components.hacs.repository] Downloading __init__.py
2019-07-21 22:46:42 DEBUG (MainThread) [custom_components.hacs.download] Donwloading https://raw.githubusercontent.com/custom-components/breaking_changes/0.3.0/custom_components/breaking_changes/__init__.py
2019-07-21 22:46:43 DEBUG (MainThread) [custom_components.hacs.download] Saving /config/custom_components/breaking_changes/__init__.py
2019-07-21 22:46:43 DEBUG (MainThread) [custom_components.hacs.repository] Downloading const.py
2019-07-21 22:46:43 DEBUG (MainThread) [custom_components.hacs.download] Donwloading https://raw.githubusercontent.com/custom-components/breaking_changes/0.3.0/custom_components/breaking_changes/const.py
2019-07-21 22:46:43 DEBUG (MainThread) [custom_components.hacs.download] Saving /config/custom_components/breaking_changes/const.py
2019-07-21 22:46:43 DEBUG (MainThread) [custom_components.hacs.repository] Downloading manifest.json
2019-07-21 22:46:43 DEBUG (MainThread) [custom_components.hacs.download] Donwloading https://raw.githubusercontent.com/custom-components/breaking_changes/0.3.0/custom_components/breaking_changes/manifest.json
2019-07-21 22:46:43 DEBUG (MainThread) [custom_components.hacs.download] Saving /config/custom_components/breaking_changes/manifest.json
2019-07-21 22:46:43 DEBUG (MainThread) [custom_components.hacs.repository] Downloading sensor.py
2019-07-21 22:46:43 DEBUG (MainThread) [custom_components.hacs.download] Donwloading https://raw.githubusercontent.com/custom-components/breaking_changes/0.3.0/custom_components/breaking_changes/sensor.py
2019-07-21 22:46:43 DEBUG (MainThread) [custom_components.hacs.download] Saving /config/custom_components/breaking_changes/sensor.py
2019-07-21 22:46:43 INFO (MainThread) [custom_components.hacs.repository] (custom-components/breaking_changes) - installation completed in 2 seconds
2019-07-21 22:46:43 DEBUG (MainThread) [custom_components.hacs.store] Saving data
2019-07-21 22:46:43 DEBUG (MainThread) [custom_components.hacs.web] Endpoint (repository) called
2019-07-21 22:46:44 DEBUG (MainThread) [custom_components.hacs.web] Endpoint (static) called
2019-07-21 22:46:44 DEBUG (MainThread) [custom_components.hacs.web] Endpoint (static) called
2019-07-21 22:46:44 DEBUG (MainThread) [custom_components.hacs.web] Endpoint (static) called
2019-07-21 22:46:44 DEBUG (MainThread) [custom_components.hacs.web] Endpoint (static) called
2019-07-21 22:46:44 DEBUG (MainThread) [custom_components.hacs.web] Endpoint (static) called
2019-07-21 22:46:48 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.potential_breaking_changes fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 221, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 378, in async_device_update
    await self.async_update()
  File "/config/custom_components/breaking_changes/sensor.py", line 29, in async_update
    await update_data(self.hass)
  File "/config/custom_components/breaking_changes/__init__.py", line 95, in update_data
    return True
AttributeError: 'Version' object has no attribute 'get_local_version'
```

**Comment by ludeeus** [comment]
no you are not.
`get_local_version` does no longer exist in that version <https://github.com/custom-components/breaking_changes/search?q=get_local_version&unscoped_q=get_local_version>

**Comment by etricky** [comment]
What do you mean by that? I updated to 0.3.0 via HACS (as you can see in the logs) and in there it said that was the current version of the component. I tried to reinstall it via HACS and I always get the same result.

**Comment by ludeeus** [comment]
You are missing a crucial part you **need** to **restart** home assistant **every time** you change/upgrade a custom component.

**Comment by etricky** [comment]
I restarted HA after the upgrade in HACS. I got working now but had to uninstall it and install it again.
